### ISSUE TITLE
Checklist syntax is not working

### ISSUE THREAD

**Issue by akshatnema** [Aksh-Bansal-dev/markdown-editor#1]
# Description
The website of this markdown editor is not supporting to make a  valid checklist, using the syntax of markdown. 

# Preview of Error
![image](https://user-images.githubusercontent.com/76521428/140384816-96263ffc-8a4c-42bd-a922-2951d6f11651.png)

# Expected behavior 
![image](https://user-images.githubusercontent.com/76521428/140385268-e94dd501-3841-4046-9037-85896f918011.png)

**Comment by Aksh-Bansal-dev** [comment]
Thanks for the issue. I will soon roll out this feature.
